CREATE TABLE `Message` (
  `id` VARCHAR(191) NOT NULL,
  `text` TEXT NOT NULL,
  `isUserMessage` BOOLEAN NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `userId` VARCHAR(191),
  `fileId` VARCHAR(191),
  PRIMARY KEY (`id`),
  FOREIGN KEY (`userId`) REFERENCES `User`(`id`),
  FOREIGN KEY (`fileId`) REFERENCES `File`(`id`)
);